#!/usr/bin/env bash

# Syntax verification [package: 'shellcheck']
# $ shellcheck <script>.sh

# Ensure script safety
set -Eeuo pipefail

#### Arguments ####

#### Variables #####

#### Functions ####

#### Main ####
